name: CI to Docker Hub latest

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ## 1. Checkout repo ##
      - name: Check Out Repo 
        uses: actions/checkout@v2

      ## 2. Login to Docker Hub using PAT ##
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      ## 3. Setup Docker Buildix ##
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
      ## 4. Adding docker image to Docker hub, using local Docker file ##
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: washrafayoub/easy-web-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      ## 5. Check on the added image ##
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      ## 6. Build a cash for the added image ## ** This step is needed only once I guess **
      #- name: Cache Docker layers
      #  uses: actions/cache@v2
      #  with:
      #    path: /tmp/.buildx-cache
      #    key: ${{ runner.os }}-buildx-${{ github.sha }}
      #    restore-keys: |
      #      ${{ runner.os }}-buildx-

      ## 7. Start running the tool ## Try the docker commands first
      - name: Inspect and Run image
        if: github.event_name != 'pull_request'
        run: |
          docker pull washrafayoub/easy-web-app:latest
          #docker image inspect washrafayoub/easy-web-app:latest
          docker run washrafayoub/easy-web-app:latest
      ## 8. Run Unit tests ##
