name: ci_docker2

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          key: cf18baf8-5a67-4835-95e9-2d2228570f08
          #username: ${{ secrets.DOCKERHUB_USERNAME }} 
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
          #registry: ghcr.io
          #username: ${{ github.repository_owner }}
          #password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        #uses: docker push washrafayoub/washraf_repo:tagname
        with:
          push: true
          tags: user/app:latest
          build-args: |
            arg1=value1
            arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
